### ISSUE TITLE
Try to turn on cobaya but got an error

### ISSUE THREAD

**Issue by Saber-of-QFT** [joezuntz/cosmosis#1]
Dear Joezuntz,
      I met an error when running a metropolis sampler using cosmosis.
      I install cosmosis using conda, following the step you present in https://github.com/joezuntz/cosmosis. And I install cobaya using 'python pip install cobaya --upgrade' after activate ./conda-env
     Then I try to run the des-y1.ini, but change "sampler = test" to "sampler = metropolis", and in the [metropolis] module, I set "cobaya = T". But I get this respond

`Using default covariance 1% of param widths
Using the Cobaya proposal
Pipeline ran okay.
    Likelihood 2pt = 5237.371107905489
Likelihood total = 5237.371107905489
Traceback (most recent call last):
  File "/home/saberofqft/conda-env/bin/cosmosis", line 4, in <module>
    status = cosmosis.main.main()
  File "/home/saberofqft/conda-env/lib/python3.9/site-packages/cosmosis/main.py", line 360, in main
    return run_cosmosis(args,pool)
  File "/home/saberofqft/conda-env/lib/python3.9/site-packages/cosmosis/main.py", line 293, in run_cosmosis
    sampler.config()
  File "/home/saberofqft/conda-env/lib/python3.9/site-packages/cosmosis/samplers/metropolis/metropolis_sampler.py", line 78, in config
    self.sampler = metropolis.MCMC(start, posterior, covmat,
  File "/home/saberofqft/conda-env/lib/python3.9/site-packages/cosmosis/samplers/metropolis/metropolis.py", line 48, in __init__
    self.proposal = cobaya_proposal.CobayaProposalWrapper(
TypeError: __init__() missing 1 required positional argument: 'random_state'`

    Can you help me? Thank you very much!

**Comment by joezuntz** [comment]
Thanks for spotting this! I am looking for a fix, which I am discussing here, which is the same error:
https://bitbucket.org/joezuntz/cosmosis/issues/394/try-to-turn-on-cobaya-but-got-an-error
